### ISSUE TITLE
NameError: name 'cycle_trainer' is not defined

### ISSUE THREAD

**Issue by abhineet99** [CSC2548/text2image2textGAN#6]
Traceback (most recent call last):   File "runtime.py", line 55, in <module>     cycle_trainer.train(args.cls) 
NameError: name 'cycle_trainer' is not defined

Do you have the code available for cycle_gan end to end training? It seems that this has been accepted as an argument but no implementation is available in trainer.py

**Comment by dany87kuo** [comment]
hello,Do you sucess run this repo?

**Comment by abhineet99** [comment]
Yes I did, had to make some changes though. Might be able to help if you can pin point the issues you're facing?

**Comment by dany87kuo** [comment]
@abhineet99  Thanks for yorr help!
I want to ask what environment you use?
I use conda python2.7 pytorch0.4  and torchvision 0.2.1
When I run start_pretraining.sh by this command: python runtime.py --type=pretrain_caption --dataset=flowers 
I got this error:
/home/dany/Desktop/Screenshot from 2021-06-02 04-45-25.png

**Comment by dany87kuo** [comment]
@abhineet99   Thanks for yorr help!
I want to ask what environment you use?
I use conda python2.7 pytorch0.4  and torchvision 0.2.1
When I run start_pretraining.sh by this command: python runtime.py --type=pretrain_caption --dataset=flowers 
I got this error:
/home/dany/text2image2textGAN-master/txt2image_dataset.py:28: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  self.image_paths_df = pd.read_table('data/images.txt', sep='\s+|\/+', header=None)
False
pretrain_caption
gan
  0%|                                                   | 0/100 [00:07<?, ?it/s]
Traceback (most recent call last):
  File "runtime.py", line 52, in <module>
    trainer.train(args.cls, args.interp)
  File "/home/dany/text2image2textGAN-master/trainer.py", line 140, in train
    self._pretrain_caption()
  File "/home/dany/text2image2textGAN-master/trainer.py", line 190, in _pretrain_caption
    gen_losses.append(loss_gen.cpu().data.numpy()[0])
IndexError: too many indices for array: array is 0-dimensional, but 1 were indexed
